### ISSUE TITLE
Empty Project

### ISSUE THREAD

**Issue by ElectronSz** [katendeglory/react-material-ui-tests#1]
What are you really planning to do with this project?

**Comment by katendeglory** [comment]
Hi Lwazi, I’m planning to read through the whole material-ui doc, available at (www.material-ui.com).It seems like a really good ui framework and I’ll use this repo as a testing ground as I read along the doc. 😁 Didn’t want to install dependencies on my PC for this. I’m using the PWA built by stackblitz as an online Editor, it’s pretty cool. Sent from Mail for Windows 10 From: Lwazi DlaminiSent: Friday, November 29, 2019 11:42 PMTo: katendeglory/react-material-ui-testsCc: SubscribedSubject: [katendeglory/react-material-ui-tests] Empty Project (#1) What are you really planning to do with this project?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by katendeglory** [comment]
Hi Lwazi, I’m planning to read through the whole material-ui doc, available at (www.material-ui.com).

It seems like a really good ui framework and I’ll use this repo as a testing ground as I read along the doc.

😁 Didn’t want to install heavy react dependencies on my PC for such a trivial task. I’m using the PWA built by stackblitz as an online Editor, it’s pretty cool.
